schema: http
port: 9119
ssl_certificate:
ssl_certificate_key:
tcp_health_check: true
log_level: debug
raft:
  data_dir: ./node
  tcp_address: 127.0.0.1:7000
  leader: true
location:                         # route matching for reverse proxy
  - pattern: /api
    proxy_pass:                   # URL of the reverse proxy
    - "http://localhost:8080"
    # - "http://192.168.1.2:1015"
    # - "https://192.168.1.2"
    # - "http://my-server.com"
    balance_mode: round-robin     # load balancing algorithm