name: node3
schema: http
port: 82
http_port: 9121
ssl_certificate:
ssl_certificate_key:
tcp_health_check: true
log_level: debug
router_type: default
raft:
  data_dir: ./data
  tcp_address: 127.0.0.1:5000
  leader: false
  leader_address: 127.0.0.1:9119
  snapshot_interval: 20
  snapshot_threshold: 1
  log_level: debug
  heartbeat_timeout: 10
  election_timeout: 10
location:                         # route matching for reverse proxy
  - pattern: /api
    proxy_pass:                   # URL of the reverse proxy
    - "http://localhost:8080"
    - "http://localhost:8081"
    # - "http://my-server.com"
    balance_mode: round-robin     # load balancing algorithm