POST http://localhost:9119/limiter HTTP/1.1
content-type: application/json

{
    "prefix": "/api",
    "limiterInfo": {
        "pathName": "/hello",
        "limiterType": "qps",
        "volumn": 2,
        "speed": 1,
        "duration": 0,
        "maxThread": -1
    }
};
###
POST http://localhost:9119/limiter HTTP/1.1
content-type: application/json

{
    "prefix": "/api",
    "pathName": "/index",
    "limiterType": "qps",
    "volumn": 1,
    "speed": 1,
    "duration": 500,
    "maxThread": -1
};
###
GET http://localhost/api/index
###
GET http://localhost/test/index
###
GET http://localhost/api/hello
###
GET http://localhost:9119/peers
###
GET http://localhost:9119/methods
###
GET http://localhost:9119/proxy
###
POST http://localhost:9119/methodInfo
Content-Type: application/json

{
    "pattern": "/api",
    "method": "/hello"
}
###
POST http://localhost:9119/acl
Content-Type: application/json

{
    "type": 1,
    "ipAddress": "192.168.3.1/32"
}
###
GET http://localhost:9119/getAcl
###
POST http://localhost:9119/acl
Content-Type: application/json

{
    "pattern": 0,
    "ipAddress": "127.0.0.1/32"
}
###
POST http://localhost:9119/removeProxy
Content-Type: application/json

{
    "pattern": "/api"
}
###
POST http://localhost:9119/removeHost
Content-Type: application/json

{
    "pattern": "/api",
    "host": "localhost:8080"
}
###
POST http://localhost:9119/addHost
Content-Type: application/json

{
    "pattern": "/api",
    "host": "http://localhost:8081"
}
###
GET http://localhost/api/person?name=Cheryl&age=18
###
POST http://localhost/api/people
Content-Type: application/json

{
    "name": "Cheryl",
    "age": 18
}